language: java
install: true

branches:
  only:
    - master

os: linux
dist: trusty
jdk: openjdk11

script:
  - cd backend/finance-help
  - chmod 777 ./gradlew
  - ./gradlew test --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
